@baseUrl = http://localhost:4000
# AppControllerGethello

# Rota para busca todos os recados
GET {{baseUrl}}/recados
?LIMIT=10
&OFFSET=0

### Rota para buscar um recado
GET {{baseUrl}}/recados/2

###
# Rota para criar um recado
POST {{baseUrl}}/recados
Content-Type: application/json
//informa o tipo de conteudo que estamos enviando

{
    "texto":"",
    "de": "Arthur",
    "para": "Anna",
}

### Rota para atualizar um recado
#Usamos o patch para atualizar tbm, 
#porem ele seria mais usado quando quisermos atulizar a chave de um ,dos valores que queremos atualizar
PATCH  {{baseUrl}}/recados/1
Content-Type: application/json

{
    "texto": "Recado 1",
    "lido": true
}

### Rota para deletar um recado
DELETE {{baseUrl}}/recados/2
