@baseUrl = http://localhost:4000
# AppControllerGethello

# Rota para busca todos os recados
GET {{baseUrl}}/recados
?LIMIT=10
&OFFSET=0

### Rota para buscar um recado
GET {{baseUrl}}/recados/1

###
# Rota para criar um recado
POST {{baseUrl}}/recados
Content-Type: application/json
//informa o tipo de conteudo que estamos enviando

{
    "texto":"Mamãe está indo treinar",
    "deId": 4,
    "paraId": 1
}

### Rota para atualizar um recado
#Usamos o patch para atualizar tbm, 
#porem ele seria mais usado quando quisermos atulizar a chave de um ,dos valores que queremos atualizar
PATCH  {{baseUrl}}/recados/2
Content-Type: application/json

{
    "texto": "Recado 122",
    "lido": true
}

### Rota para deletar um recado
DELETE {{baseUrl}}/recados/1


### Rota para criar um usuario



# Rota para busca todos os recados
GET {{baseUrl}}/pessoas
?LIMIT=10
&OFFSET=0

### Rota para buscar uma pessoa
GET {{baseUrl}}/pessoas/1

###
# Rota para criar uma pessoa
POST {{baseUrl}}/pessoas
Content-Type: application/json
//informa o tipo de conteudo que estamos enviando

{
    "email":"anna_julia@email.com",
    "password": "54321",
    "nome": "Anna Julia"
}

### Rota para atualizar uma pessoa
#Usamos o patch para atualizar tbm, 
#porem ele seria mais usado quando quisermos atulizar a chave de um ,dos valores que queremos atualizar
PATCH  {{baseUrl}}/pessoas/8
Content-Type: application/json

{
    "password": "33333",
    "nome": "Juju"
}

### Rota para deletar uma pessoa
DELETE {{baseUrl}}/pessoas/1

